# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rweather.proto\"F\n\x0eWeatherRequest\x12\x10\n\x08time_now\x18\x01 \x01(\x05\x12\x10\n\x08locate_x\x18\x02 \x01(\x05\x12\x10\n\x08locate_y\x18\x03 \x01(\x05\"X\n\x0fWeatherResponse\x12\r\n\x05state\x18\x01 \x01(\x08\x12\x13\n\x0blocate_name\x18\x02 \x01(\t\x12!\n\x0btemperature\x18\x03 \x03(\x0b\x32\x0c.Temperature\")\n\x0bTemperature\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12\x0c\n\x04temp\x18\x02 \x01(\x05\x32>\n\x0eWeatherService\x12,\n\x07Weather\x12\x0f.WeatherRequest\x1a\x10.WeatherResponseb\x06proto3'
)




_WEATHERREQUEST = _descriptor.Descriptor(
  name='WeatherRequest',
  full_name='WeatherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_now', full_name='WeatherRequest.time_now', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locate_x', full_name='WeatherRequest.locate_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locate_y', full_name='WeatherRequest.locate_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=87,
)


_WEATHERRESPONSE = _descriptor.Descriptor(
  name='WeatherResponse',
  full_name='WeatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='WeatherResponse.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locate_name', full_name='WeatherResponse.locate_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='WeatherResponse.temperature', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=177,
)


_TEMPERATURE = _descriptor.Descriptor(
  name='Temperature',
  full_name='Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Temperature.time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='Temperature.temp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=220,
)

_WEATHERRESPONSE.fields_by_name['temperature'].message_type = _TEMPERATURE
DESCRIPTOR.message_types_by_name['WeatherRequest'] = _WEATHERREQUEST
DESCRIPTOR.message_types_by_name['WeatherResponse'] = _WEATHERRESPONSE
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeatherRequest = _reflection.GeneratedProtocolMessageType('WeatherRequest', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERREQUEST,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:WeatherRequest)
  })
_sym_db.RegisterMessage(WeatherRequest)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), {
  'DESCRIPTOR' : _WEATHERRESPONSE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:WeatherResponse)
  })
_sym_db.RegisterMessage(WeatherResponse)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:Temperature)
  })
_sym_db.RegisterMessage(Temperature)



_WEATHERSERVICE = _descriptor.ServiceDescriptor(
  name='WeatherService',
  full_name='WeatherService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=222,
  serialized_end=284,
  methods=[
  _descriptor.MethodDescriptor(
    name='Weather',
    full_name='WeatherService.Weather',
    index=0,
    containing_service=None,
    input_type=_WEATHERREQUEST,
    output_type=_WEATHERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHERSERVICE)

DESCRIPTOR.services_by_name['WeatherService'] = _WEATHERSERVICE

# @@protoc_insertion_point(module_scope)
